### ISSUE TITLE
6.1.1 Como usuario, quiero diligenciar un nuevo proyecto

### ISSUE THREAD

**Issue by Sao912** [ISWPOLI/precise_estimate_server#29]
**Descripción de la historia**
El usuario al ingresar en la aplicación debe poder crear un nuevo proyecto a estimar

**Tareas:**

****Front-End****
- [x] Creación del formulario de gestión del proyecto
- [x] Validación del formulario
- [x] Pruebas de unidad

****Back-End****
- [x] Creación de servicios de CRUD de la gestión de proyectos
- [x] Pruebas de unidad

**Comment by Jwilchez** [comment]
Terminado en la primera fase
