### ISSUE TITLE
1.1.1 Acceso al sitio desde el dispositivo movil

### ISSUE THREAD

**Issue by Sao912** [ISWPOLI/precise_estimate_server#3]
**Descripción de la historia**
El data entry del user deber validarse y responder si el usuario existe o no
**Tareas**
- [x] Definición del lenguaje del front-end
- [x] Adaptación de la plantilla angular 2
- [x] Pruebas y despliegue

**Comment by Sao912** [comment]
Acceso al sitio desde el dispositivo movil

**Comment by Jwilchez** [comment]
Actividad completa segun commit a72e7bf8e7fe2fa02e9c810760d752db14bec84b

**Comment by Jwilchez** [comment]
Terminado en la primera fase
